name: CI & Build
on: [push, pull_request]

jobs:
  test:
    name: Test & Build
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: x86_64-linux-musl, os: ubuntu-latest, target: x86_64-unknown-linux-musl }
          - { name: x86_64-windows-msvc, os: windows-latest, target: x86_64-pc-windows-msvc }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - run: sudo apt-get install musl-tools
        if: matrix.name == 'x86_64-linux-musl'
      - run: cargo test --target ${{ matrix.target }}
      - run: cargo build --release --target ${{ matrix.target }}
        env:
            RUSTFLAGS: -C target-feature=+crt-static
      - run: strip target/${{ matrix.target }}/release/runexp
        if: matrix.name != 'x86_64-windows-msvc'
      - run: mv target/${{ matrix.target }}/release/runexp.exe target/${{ matrix.target }}/release/runexp
        if: matrix.name == 'x86_64-windows-msvc'
      - uses: actions/upload-artifact@v4
        with:
          name: runexp-${{ matrix.name }}
          path: target/${{ matrix.target }}/release/runexp
  release:
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: |
          mkdir artifacts
          mv runexp-x86_64-linux-musl/runexp artifacts/runexp-x86_64-linux-musl
          mv runexp-x86_64-windows-msvc/runexp artifacts/runexp-x86_64-windows-msvc
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
